name: release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    strategy:
      matrix:
        python-version:
          - 3.10.11
    defaults:
      run:
        shell: bash

    name: Release new API version

    steps:
      - name: Checkout API
        uses: actions/checkout@v4

      - name: Set up python v${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Generate release changelog
        run: python release-changelog.py

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "CHANGELOG.md.tmp"
